version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%' 
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - node-network

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: matheuspsilva29/node
    container_name: app
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - 3000:3000
    # depends_on:
      # - db
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: matheuspsilva29/nginx
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - app
      # - db
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
