version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - node-network

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: matheuspsilva29/node
    container_name: app
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: matheuspsilva29/nginx
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - app

    networks:
      - node-network

networks:
  node-network:
    driver: bridge
